coverage:
    precision: 2
    round: up
    range: "90...100"
    status:
        project:
            default:
                # basic
                target: auto
                threshold: 2%
                if_not_found: success
                if_ci_failed: error
                informational: false
                only_pulls: true
        patch:
            default:
                # basic
                target: auto
                threshold: 20%
                # advanced
                if_no_uploads: error
                if_not_found: success
                if_ci_failed: error
                only_pulls: true
