name: Docker

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - 'docs/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      USER: sdss
      APP: flicamera
    steps:
      - name: Set docker tags
        id: set-tags
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]
          then
            echo ::set-output name=TAGS::$USER/$APP:latest
          elif [[ $GITHUB_REF == refs/heads/* ]]
          then
            BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/[\/]/_/g')
            echo ::set-output name=TAGS::$USER/$APP:$BRANCH
          else
            echo ::set-output name=TAGS::$USER/$APP:${GITHUB_REF#refs/tags/}
          fi
      - name: Show tags
        run: echo ${{ steps.set-tags.outputs.TAGS }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Authorise Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAC_TOKEN }} # from Secrets
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: etc/Dockerfile
          context: ..
          tags: ghcr.io/${{ steps.set-tags.outputs.TAGS }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
